apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
stringData:
  SECRET_KEY: Ae2(yx4)y&Ggh3_s=5yj-zH$pebxs~dg44x)-k&k_x3z*f%9e*
  NAME: todoapp
  USER: todoapp
  PASSWORD: todopassword
  HOST: mysql-0.mysql.mysql.svc.cluster.local